// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdAayQzOReJ0Fs_-o5Epn2u9RcRjfYoXo',
    appId: '1:250943322957:web:e52c0fe38d499e7175d504',
    messagingSenderId: '250943322957',
    projectId: 'gestionstocks-7ffb4',
    authDomain: 'gestionstocks-7ffb4.firebaseapp.com',
    storageBucket: 'gestionstocks-7ffb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaAEcyS04tu1i_zAtDHvrsb0fworRaQM',
    appId: '1:250943322957:android:8c778ea6c4da29cf75d504',
    messagingSenderId: '250943322957',
    projectId: 'gestionstocks-7ffb4',
    storageBucket: 'gestionstocks-7ffb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKeJzDDiaKjKK7PENA_SB_9SUAw8QgphQ',
    appId: '1:250943322957:ios:f179251572ccdeca75d504',
    messagingSenderId: '250943322957',
    projectId: 'gestionstocks-7ffb4',
    storageBucket: 'gestionstocks-7ffb4.appspot.com',
    iosBundleId: 'com.example.gestionStockFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKeJzDDiaKjKK7PENA_SB_9SUAw8QgphQ',
    appId: '1:250943322957:ios:33fd16ed8ae3917275d504',
    messagingSenderId: '250943322957',
    projectId: 'gestionstocks-7ffb4',
    storageBucket: 'gestionstocks-7ffb4.appspot.com',
    iosBundleId: 'com.example.gestionStockFlutter.RunnerTests',
  );
}
